# Generated by Django 5.1.5 on 2025-02-07 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Введите заголовок статьи', max_length=200, verbose_name='Заголовок')),
                ('content', models.TextField(blank=True, help_text='Введите содержимое статьи', null=True, verbose_name='Содержимое')),
                ('image', models.ImageField(blank=True, help_text='Загрузите изображение', null=True, upload_to='blog_image', verbose_name='Изображение')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('is_published', models.BooleanField(default=True)),
                ('views_count', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'статья',
                'verbose_name_plural': 'статьи',
                'db_table': 'Статьи',
            },
        ),
    ]
